spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 40cd8cda-2fb3-4e99-93b1-8e310cf6d63e
            client-secret: nX8Uc9E7K5G-uq_1DJO.P.eXd5vt_cKK_E
            redirect-uri: https://azapp-ad-app.azurewebsites.us/login/oauth2/code/azure

azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: 0107f7b6-fa03-4b7a-a7bf-9b09c6b0c87a
    # Specifies your App Registration's Application ID:
    client-id: 40cd8cda-2fb3-4e99-93b1-8e310cf6d63e
    # Specifies your App Registration's secret key:
    client-secret: nX8Uc9E7K5G-uq_1DJO.P.eXd5vt_cKK_E
    redirect-uri-template: https://azapp-ad-app.azurewebsites.us/login/oauth2/code/azure
    # Specifies the list of Active Directory groups to use for authorization:
    user-group:
      allowed-group-names: group1, group2, Users
    authorization-clients:
      graph:
        scopes:
            - https://graph.microsoft.com/User.Read
            - https://graph.microsoft.com/Directory.AccessAsUser.All

welcomeMessage: PROD Message
