#server:
#  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 03912d0b-bb99-473d-8a76-e6a228da997f
            client-secret: 2bz9hNYDDwI1_~xl.M4b5S4kxQ.04X_112
            
azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: c7e0de68-75b5-4003-879d-5c1ed5892f13
    # Specifies your App Registration's Application ID:
    client-id: 03912d0b-bb99-473d-8a76-e6a228da997f
    # Specifies your App Registration's secret key:
    client-secret: 2bz9hNYDDwI1_~xl.M4b5S4kxQ.04X_112
    # Specifies the list of Active Directory groups to use for authorization:
    user-group:
      allowed-group-names: group1, group2, Users

welcomeMessage: Default Message!

debug: true
