spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: 3fa6432f-cd50-4583-bf4a-e2fc6b170caf
            client-secret: ~_Y.leGk~aU99uX8_6Uk.zu~Laf1WTR1ja
            redirect-uri: https://azapp-ad-app-dev.azurewebsites.us/login/oauth2/code/azure

azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: 0107f7b6-fa03-4b7a-a7bf-9b09c6b0c87a
    # Specifies your App Registration's Application ID:
    client-id: 3fa6432f-cd50-4583-bf4a-e2fc6b170caf
    # Specifies your App Registration's secret key:
    client-secret: ~_Y.leGk~aU99uX8_6Uk.zu~Laf1WTR1ja
    redirect-uri-template: https://azapp-ad-app-dev.azurewebsites.us/login/oauth2/code/azure
    # Specifies the list of Active Directory groups to use for authorization:
    user-group:
      allowed-group-names: group1, group2, Users
    authorization-clients:
      graph:
        scopes:
            - https://graph.microsoft.com/User.Read
            - https://graph.microsoft.com/Directory.AccessAsUser.All

welcomeMessage: DEV Message
