name: AzureADPOC CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package
        working-directory: AzureADApp
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'azapp-ad-app'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }} 
          package: '${{ github.workspace }}/AzureADApp/target/*.jar' 
          slot-name: 'dev' 
